<section class="section dark-background">

      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center" data-aos="zoom-out">
            <br><br><h1>SILAYUR MANTAP <br>UPT PELABUHAN PERRIKANAN PANTAI BULU</h1>
          </div>
        </div>
      </div>

</section>

<!-- Call To Action Section -->
<section id="call-to-action" class="call-to-action section dark-background">

  <img src="assets/img/bg.jpg" alt="">

  <div class="container">

    <div class="row" data-aos="zoom-in" data-aos-delay="100">
      <div class="col-xl-9 text-center text-xl-start">
        <h3>S I L A Y U R M A N T A P</h3>
        <p>Merupakan inovasi pengguna jasa yang dapat dilakukan secara mandiri dengan integrasi konfirmasi whatsapp untuk lebih transaparan dan bisa dilacak sesuai nomor register pelayanan.</p>
        </div>
      <div class="col-xl-3 cta-btn-container text-center">
        <a class="cta-btn align-middle" href="https://pppbulu.dkp.jatimprov.go.id/silayurmantap/formstblkb">WebSite</a>
      </div>
    </div>
    
  </div>

</section><!-- /Call To Action Section -->

<!-- Skills Section -->
<section class="skills section">

  <div class="container" data-aos="fade-up" data-aos-delay="100">

    <div class="row">

      <div class="col-lg-6 d-flex align-items-center" style="width: 100%; max-width: 400px; margin: 0 auto;">
        <img src="assets/img/SILAYURMANTAP.png" class="img-fluid" alt="" style="width: 100%; height: auto; object-fit: contain;">
      </div>

      <div class="col-lg-6 pt-4 pt-lg-0 content">

        <h3>Si-LAYUR MANTAP</h3>
        <p class="fst-italic">
        Merupakan inovasi pengguna jasa yang dapat dilakukan secara mandiri dengan integrasi konfirmasi whatsapp untuk lebih transaparan dan bisa dilacak sesuai nomor register pelayanan</p>
      </div>
    </div>

  </div>

</section>

<!-- Faq 2 Section -->
<section id="faq-2" class="faq-2 section light-background">

  <!-- Section Title -->
  <div class="container section-title" data-aos="fade-up">
    <h2>Fitur-Fitur Si-LAYUR MANTAP</h2>
  </div><!-- End Section Title -->

  <div class="container">

    <div class="row justify-content-center">

      <div class="col-lg-10">

        <div class="faq-container">

          <div class="faq-item" data-aos="fade-up" data-aos-delay="200">
            <i class="faq-icon bi bi-circle"></i>
            <h3>PERMOHONAN PPKP (PERSETUJUAN PENGADAAN KAPAL PERIKANAN)</h3>
            <div class="faq-content">
              <p>Fitur pengingat kepada Pengguna Jasa Terkait Jatuh Tempo terkait pembayaran Pemanfaatan Sarana Prasarana</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

          <div class="faq-item" data-aos="fade-up" data-aos-delay="300">
            <i class="faq-icon bi bi-circle"></i>
            <h3>PERMOHONAN LAIK KAPAL PERIKANAN</h3>
            <div class="faq-content">
              <p>Fitur Lacak Pelayanan merupakan inovasi untuk mengetahui proses pelayanan yang kita terima hingga selesai dengan waktu seminimal mungkin sesuai prosedur</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

          <div class="faq-item" data-aos="fade-up" data-aos-delay="400">
            <i class="faq-icon bi bi-circle"></i>
            <h3>PERMOHONAN KETERANGAN DOCKING KAPAL</h3>
            <div class="faq-content">
              <p>Fitur Lacak Pelayanan merupakan inovasi untuk mengetahui proses pelayanan yang kita terima hingga selesai dengan waktu seminimal mungkin sesuai prosedur</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

          <div class="faq-item" data-aos="fade-up" data-aos-delay="500">
            <i class="faq-icon bi bi-circle"></i>
            <h3>PERMOHONAN NIB</h3>
            <div class="faq-content">
              <p>Fitur Lacak Pelayanan merupakan inovasi untuk mengetahui proses pelayanan yang kita terima hingga selesai dengan waktu seminimal mungkin sesuai prosedur</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

          <div class="faq-item" data-aos="fade-up" data-aos-delay="600">
            <i class="faq-icon bi bi-circle"></i>
            <h3>PERMOHONAN REKOMENDASI BBM SUBSIDI UNTUK NELAYAN?</h3>
            <div class="faq-content">
              <p>Fitur Lacak Pelayanan merupakan inovasi untuk mengetahui proses pelayanan yang kita terima hingga selesai dengan waktu seminimal mungkin sesuai prosedur</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

          <div class="faq-item" data-aos="fade-up" data-aos-delay="600">
            <i class="faq-icon bi bi-circle"></i>
            <h3>TRACKING PERMOHANAN PELAYANAN</h3>
            <div class="faq-content">
              <p>Fitur Lacak Pelayanan merupakan inovasi untuk mengetahui proses pelayanan yang kita terima hingga selesai dengan waktu seminimal mungkin sesuai prosedur</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

          <div class="faq-item" data-aos="fade-up" data-aos-delay="600">
            <i class="faq-icon bi bi-circle"></i>
            <h3>PELAYANAN MANDIRI DARI RUMAH</h3>
            <div class="faq-content">
              <p>Fitur Lacak Pelayanan merupakan inovasi untuk mengetahui proses pelayanan yang kita terima hingga selesai dengan waktu seminimal mungkin sesuai prosedur</p>
            </div>
            <i class="faq-toggle bi bi-chevron-right"></i>
          </div><!-- End Faq item-->

        </div>

      </div>

    </div>

  </div>

</section><!-- /Faq 2 Section -->